### ISSUE TITLE
SyntaxWarning: "is" with a literal. Did you mean "=="?

### ISSUE THREAD

**Issue by ikirt** [0v3rride/Enum4LinuxPy#33]
## Expected Behavior
usage: python Enum4LinuxPy.py -t <target> <options>
    E.g:
    python Enum4LinuxPy.py -t 10.10.x.x -a
    python Enum4LinuxPy.py -t 10.20.x.x -l
    python Enum4LinuxPy.py -t 192.168.x.x -R 1000-2000 500-600 -k administrator wsusadmin exchadmin root guest admin

    NOTE that -R or -k take a list as arguments and only require a space separation delimitation)
Enum4LinuxPy https://github.com/0v3rride (Ryan Gore): error: the following arguments are required: -t

## Actual Behavior
/home/abcdefg/Documents/Enum4LinuxPy/Enum4LinuxPy.py:120: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if uargs.p is None or uargs.p is "":
/home/abcdefg/Documents/Enum4LinuxPy/Enum4LinuxPy.py:127: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if sys.platform.lower() is "windows":
/home/abcdefg/Documents/Enum4LinuxPy/Enum4LinuxPy.py:136: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if response.returncode is 0 and verbose:
/home/abcdefg/Documents/Enum4LinuxPy/Enum4LinuxPy.py:138: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  elif response.returncode is not 0:
/home/abcdefg/Documents/Enum4LinuxPy/Enum4LinuxPy.py:147: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if response.returncode is 0 and verbose:
/home/abcdefg/Documents/Enum4LinuxPy/Enum4LinuxPy.py:149: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  elif response.returncode is not 0:
/home/abcdefg/Documents/Enum4LinuxPy/Enum4LinuxPy.py:422: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if (args.w is None or args.w is "" or args.w is " "):
/home/abcdefg/Documents/Enum4LinuxPy/Enum4LinuxPy.py:422: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if (args.w is None or args.w is "" or args.w is " "):
/home/abcdefg/Documents/Enum4LinuxPy/Enum4LinuxPy.py:486: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if (group is "domain"):
/home/abcdefg/Documents/Enum4LinuxPy/Enum4LinuxPy.py:498: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if (group is "domain"):
/home/abcdefg/Documents/Enum4LinuxPy/Enum4LinuxPy.py:738: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if not output or output is "":
usage: python Enum4LinuxPy.py -t <target> <options>
    E.g:
    python Enum4LinuxPy.py -t 10.10.x.x -a
    python Enum4LinuxPy.py -t 10.20.x.x -l
    python Enum4LinuxPy.py -t 192.168.x.x -R 1000-2000 500-600 -k administrator wsusadmin exchadmin root guest admin

    NOTE that -R or -k take a list as arguments and only require a space separation delimitation)
Enum4LinuxPy https://github.com/0v3rride (Ryan Gore): error: the following arguments are required: -t

## Steps to Reproduce the Problem

  1. Run program normally using python3

## Specifications

  - Version: current
  - Platform: blackarch
  - Subsystem: python 3.8

## Fix

Replace explicit 'is' with '=='.

## Notes
I have fixed this locally if you want me to do a PR.

**Comment by 0v3rride** [comment]
Hi ikrit,

According to the PyCharm IDE the initial syntax is correct. Albeit, there's a couple of other things that I could clean up that I'm not too worried about at the moment.

![image](https://user-images.githubusercontent.com/35246589/74765267-dc938600-5248-11ea-9eac-e3d14ac85376.png)

![image](https://user-images.githubusercontent.com/35246589/74765355-05b41680-5249-11ea-9673-211bee79c4b4.png)

I see that you're using Blackarch and this script was built on a Kali machine. Do you receive any errors that stops the script from running or completing besides the syntax warnings?

**Comment by mpgn** [comment]
It's because he uses python3.8 @0v3rride ;)

**Comment by 0v3rride** [comment]
Closing this issue. The syntax warnings you are receiving seem to be specific to Python 3.8. Run the script using Python 3/3.7.
