### ISSUE TITLE
SyntaxWarning errors

### ISSUE THREAD

**Issue by smbsid** [0v3rride/Enum4LinuxPy#35]
When running the script; I always get this error on top:

/opt/Enum4LinuxPy/Enum4LinuxPy.py:120: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if uargs.p is None or uargs.p is "":
/opt/Enum4LinuxPy/Enum4LinuxPy.py:127: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if sys.platform.lower() is "windows":
/opt/Enum4LinuxPy/Enum4LinuxPy.py:136: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if response.returncode is 0 and verbose:
/opt/Enum4LinuxPy/Enum4LinuxPy.py:138: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  elif response.returncode is not 0:
/opt/Enum4LinuxPy/Enum4LinuxPy.py:147: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if response.returncode is 0 and verbose:
/opt/Enum4LinuxPy/Enum4LinuxPy.py:149: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  elif response.returncode is not 0:
/opt/Enum4LinuxPy/Enum4LinuxPy.py:422: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if (args.w is None or args.w is "" or args.w is " "):
/opt/Enum4LinuxPy/Enum4LinuxPy.py:422: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if (args.w is None or args.w is "" or args.w is " "):
/opt/Enum4LinuxPy/Enum4LinuxPy.py:486: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if (group is "domain"):
/opt/Enum4LinuxPy/Enum4LinuxPy.py:498: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if (group is "domain"):
/opt/Enum4LinuxPy/Enum4LinuxPy.py:738: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if not output or output is "":
Password:

**Comment by 0v3rride** [comment]
If you're running the script via Python 3.8 you will get these warnings. This script was created when 3.7 the current version. See closed issue #33

**Comment by smbsid** [comment]
Alright, thanks
